language: node_js
cache:
  directories:
    - node_modules
node_js:
- v4
- v5
- v6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - MAILGUN_KEY=mailgunKey
  - MASTER_KEY=masterKey
  - DOMAIN_NAME=domainName
  - DEFAULT_EMAIL="default@email.com"
  - JWT_SECRET=jwtSecret
